# Generated by TradingCodex on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpExternalPermissionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("router_name", models.CharField(max_length=160)),
                ("external_name", models.CharField(max_length=200)),
                ("principal_id", models.CharField(default="unknown", max_length=128)),
                ("role", models.CharField(blank=True, max_length=128)),
                ("workflow_run_id", models.CharField(blank=True, max_length=160)),
                ("request_hash", models.CharField(max_length=64)),
                ("arguments_summary", models.JSONField(blank=True, default=dict)),
                ("approval_scope", models.CharField(default="single_call", max_length=32)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.CharField(blank=True, max_length=128)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                (
                    "external_tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_requests",
                        to="mcp.mcpexternaltool",
                    ),
                ),
            ],
            options={
                "verbose_name": "external MCP permission request",
                "verbose_name_plural": "external MCP permission requests",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
