from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class HarnessComponent:
    id: str
    label: str
    summary: str
    status: str
    tags: tuple[str, ...]
    surfaces: dict[str, tuple[str, ...]]
    depends_on: tuple[str, ...]
    owned_capabilities: tuple[str, ...]
    validation: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "label": self.label,
            "summary": self.summary,
            "status": self.status,
            "tags": list(self.tags),
            "surfaces": {key: list(values) for key, values in self.surfaces.items()},
            "depends_on": list(self.depends_on),
            "owned_capabilities": list(self.owned_capabilities),
            "validation": list(self.validation),
        }


HARNESS_COMPONENTS: tuple[HarnessComponent, ...] = (
    HarnessComponent(
        id="fixed-role-dispatch",
        label="Fixed Role Dispatch",
        summary="Maintains exact Codex V2 role identity, principal-bound artifact storage, and no-overlap handoffs without a server scheduler.",
        status="core",
        tags=("guardrail.guidance", "guardrail.information_barrier", "improvement.workflow_quality"),
        surfaces={
            "instructions": ("head-manager", "AGENTS"),
            "skills": ("tcx-plan", "tcx-workflow", "tcx-automate"),
            "services": ("agents", "analysis_runs", "mcp_runtime"),
            "mcp": ("begin_analysis_run", "create_research_artifact"),
            "files": (
                ".tradingcodex/generated/model-policy-manifest.json",
            ),
            "templates": ("codex-base", "fixed-subagents", "repo-skills"),
            "tests": ("generated-workspace", "subagent-roster"),
        },
        depends_on=(),
        owned_capabilities=("workflow.dispatch_fixed_roles",),
        validation=("pytest", "generated workspace contract"),
    ),
    HarnessComponent(
        id="codex-native-orchestration",
        label="Codex Native Orchestration",
        summary="Lets Head Manager interpret multilingual requests and dynamically choose, wait for, and revise fixed-role work.",
        status="core",
        tags=("guardrail.guidance", "improvement.workflow_quality"),
        surfaces={
            "instructions": ("head-manager", "AGENTS"),
            "skills": ("tcx-plan", "tcx-workflow", "tcx-automate"),
            "hooks": ("SessionStart transport", "UserPromptSubmit transport"),
            "services": ("analysis_runs", "agents"),
            "mcp": ("begin_analysis_run", "create_research_artifact", "get_research_artifact"),
            "templates": ("codex-base", "repo-skills"),
            "tests": ("routing", "generated-workspace"),
        },
        depends_on=("fixed-role-dispatch",),
        owned_capabilities=("workflow.codex_native_orchestration",),
        validation=("pytest", "generated workspace contract", "Codex-native smoke"),
    ),
    HarnessComponent(
        id="investment-brain-plugins",
        label="Investment Brain Plugins",
        summary="Authors privacy-reviewed user-owned sources, validates and versions installed bundles, and projects explicit Head Manager inquiry overlays while sealing provenance into runs, artifacts, and Decision Memory.",
        status="core",
        tags=("guardrail.guidance", "improvement.skill_evolution", "improvement.research_memory"),
        surfaces={
            "instructions": ("head-manager",),
            "skills": ("tcx-workflow", "tcx-brain", "investment-brain-*"),
            "services": (
                "investment_brains",
                "agents",
                "analysis_runs",
                "artifact_bindings",
                "research",
                "decision_packages",
                "viewer",
            ),
            "cli": ("investment-brains",),
            "files": (
                ".tradingcodex/investment-brains/registry.json",
                ".tradingcodex/investment-brains/packages/*",
                ".agents/skills/investment-brain-*",
                "investment-brains/investment-brain-*",
                ".tradingcodex/mainagent/runs/*/run.json",
                ".tradingcodex/mainagent/runs/*/artifact-bindings/*.json",
            ),
            "tests": (
                "investment-brain-registry",
                "investment-brain-provenance",
                "investment-brain-prompt-layers",
                "artifact-authentication",
            ),
        },
        depends_on=("codex-native-orchestration", "fixed-role-dispatch", "research-memory"),
        owned_capabilities=(
            "investment_brain.registry",
            "investment_brain.explicit_projection",
            "investment_brain.local_authoring",
            "investment_brain.run_provenance",
        ),
        validation=("pytest", "generated workspace contract", "Codex-native Brain smoke"),
    ),
    HarnessComponent(
        id="workflow-quality-gates",
        label="Artifact And Judgment Quality",
        summary="Defines artifact quality, Decision Quality Spine, independent judgment review, claim discipline, and synthesis lineage without a Django workflow loop.",
        status="core",
        tags=("guardrail.guidance", "improvement.workflow_quality"),
        surfaces={
            "skills": ("tcx-plan", "tcx-workflow", "tcx-automate", "tcx-judgment"),
            "services": ("artifact_quality", "research", "viewer"),
            "mcp": ("create_research_artifact", "get_research_artifact"),
            "api": ("GET /api/viewer/artifacts/{artifact_id}",),
            "frontend": ("Library",),
            "files": ("trading/research/*.md", "trading/reports/**/*.md"),
            "templates": ("repo-skills",),
            "tests": ("quality-scenarios", "routing"),
        },
        depends_on=("codex-native-orchestration", "fixed-role-dispatch"),
        owned_capabilities=("workflow.quality_gate", "workflow.decision_quality_spine", "workflow.agent_judgment_review"),
        validation=("pytest", "routing scenario tests"),
    ),
    HarnessComponent(
        id="decision-package",
        label="Decision Package",
        summary="Freezes lightweight analysis-run provenance, accepted artifact lineage, forecasts, context bindings, blocked actions, and decision-time evidence for later review.",
        status="experimental",
        tags=("guardrail.guidance", "improvement.workflow_quality", "improvement.research_memory"),
        surfaces={
            "services": ("decision_packages", "harness"),
            "cli": ("workflow begin", "workflow show", "decision"),
            "files": ("trading/decisions/*.md", "trading/decisions/*.decision-snapshot.json", ".tradingcodex/mainagent/runs/*/run.json"),
            "frontend": ("Library",),
            "tests": ("decision-package", "routing"),
        },
        depends_on=("codex-native-orchestration", "workflow-quality-gates", "research-memory"),
        owned_capabilities=("workflow.decision_package",),
        validation=("pytest", "generated workspace contract"),
    ),
    HarnessComponent(
        id="build-turn-authorization",
        label="Workspace Turn Authorization",
        summary="Binds normalized first-meaningful-line `$tcx-build`, `$tcx-brain`, and `$tcx-strategy` invocations to separate current-turn capability scopes while leaving filesystem permission to Codex and financial execution to canonical service gates.",
        status="core",
        tags=("guardrail.guidance", "guardrail.enforcement", "improvement.workflow_quality"),
        surfaces={
            "instructions": ("head-manager",),
            "skills": ("tcx-server", "tcx-build", "tcx-brain", "tcx-strategy"),
            "hooks": ("SessionStart", "UserPromptSubmit", "PreToolUse", "PermissionRequest", "Stop"),
            "services": ("build_gateway", "startup_status", "agents", "investment_brains", "brokers"),
            "cli": ("build status", "update status", "connectors"),
            "mcp_tools": (
                "get_update_status",
                "get_connector_build_status",
                "manage_strategy",
                "manage_investment_brain",
                "register_broker_connector",
                "render_broker_connector_scaffold",
                "validate_broker_connector_build",
            ),
            "tests": ("build-turn-grant", "build-hook", "generated-workspace", "connector-build"),
        },
        depends_on=("responsibility-boundary-contract", "broker-center", "execution-boundary"),
        owned_capabilities=(
            "build.turn_authorization",
            "brain.turn_authorization",
            "strategy.turn_authorization",
            "build.self_update",
            "build.connector_scaffold",
        ),
        validation=("pytest", "startup service mismatch diagnostics", "generated workspace contract", "Codex smoke checks"),
    ),
    HarnessComponent(
        id="versioned-workspace",
        label="Versioned Workspace",
        summary="Keeps every generated workspace in a user-owned Git worktree with privacy-first ignore rules and no implicit stage, commit, remote, or publication action.",
        status="core",
        tags=("guardrail.guidance", "guardrail.information_barrier", "improvement.validation_feedback"),
        surfaces={
            "services": ("workspace_git", "runtime", "workspaces"),
            "cli": ("attach", "update", "workspace status", "doctor"),
            "files": (".git", ".gitignore", ".tradingcodex/workspace.json"),
            "tests": ("workspace-git-contract", "generated-workspace"),
        },
        depends_on=("responsibility-boundary-contract",),
        owned_capabilities=("workspace.git_contract", "workspace.privacy_ignore"),
        validation=("pytest", "generated workspace contract", "workspace Git smoke"),
    ),
    HarnessComponent(
        id="artifact-quality-contract",
        label="Artifact Quality Contract",
        summary="Evaluates workspace artifacts, Evidence Run Cards, Validation Cards, source snapshots, and forecast ledgers for source/as-of posture, source trust, data-boundary warnings, claim tags, handoff state, confidence, missing evidence, improve records, judgment-review fields, and routing metadata.",
        status="core",
        tags=("guardrail.guidance", "improvement.workflow_quality", "improvement.research_memory"),
        surfaces={
            "services": ("artifact_quality", "research"),
            "cli": ("quality-check --strict", "research create", "research run-card", "research validation-card"),
            "schemas": ("research_artifact.schema.json",),
            "files": ("*.run-card.json", "*.validation-card.json", "trading/research/source-snapshots/*.json", "trading/forecasts/*.jsonl"),
            "templates": ("enforcement-guardrails", "repo-skills", "codex-base"),
            "tests": ("artifact-quality", "research-memory"),
        },
        depends_on=("workflow-quality-gates", "research-memory"),
        owned_capabilities=("artifact.quality_contract", "forecast.ledger_contract"),
        validation=("pytest", "generated workspace contract", "quality-check --strict"),
    ),
    HarnessComponent(
        id="context-efficiency-contract",
        label="Context Efficiency Contract",
        summary="Keeps agent workflows bounded through compact briefs, artifact references, context summaries, source snapshot IDs, and targeted full-artifact reads.",
        status="core",
        tags=("guardrail.guidance", "guardrail.information_barrier", "improvement.workflow_quality", "improvement.context_efficiency"),
        surfaces={
            "instructions": ("head-manager", "AGENTS"),
            "skills": ("tcx-plan", "tcx-workflow"),
            "services": ("harness", "artifact_quality", "context_budget", "research"),
            "cli": ("subagents context-audit --strict",),
            "schemas": ("research_artifact.schema.json",),
            "tests": ("context-efficiency", "generated-workspace"),
        },
        depends_on=("fixed-role-dispatch", "artifact-quality-contract", "research-memory"),
        owned_capabilities=("context.efficiency_contract",),
        validation=("pytest", "generated workspace contract", "quality-check context_efficiency", "subagents context-audit --strict"),
    ),
    HarnessComponent(
        id="responsibility-boundary-contract",
        label="Responsibility Boundary Contract",
        summary="Separates durable role identity, tool permissions, skill procedures, artifact contracts, and projection ownership so changes stay local.",
        status="core",
        tags=("guardrail.guidance", "guardrail.information_barrier", "improvement.workflow_quality", "improvement.skill_evolution"),
        surfaces={
            "instructions": ("head-manager",),
            "skills": ("repo skill boundary tests",),
            "services": ("agents", "harness", "components"),
            "docs": ("roles-skills-and-workflows", "generated-workspaces", "components"),
            "tests": ("skill-boundary", "component-registry"),
        },
        depends_on=("fixed-role-dispatch", "skill-improvement-loop"),
        owned_capabilities=("responsibility.boundary_contract",),
        validation=("pytest", "skill boundary tests", "generated workspace contract"),
    ),
    HarnessComponent(
        id="research-memory",
        label="Research Memory",
        summary="Stores principal-bound workspace research and projects rebuildable research and cross-artifact indexes without replacing file-native sources of truth.",
        status="core",
        tags=("improvement.research_memory",),
        surfaces={
            "services": ("research", "artifact_catalog"),
            "mcp_tools": ("create_research_artifact", "search_research_artifacts", "list_artifact_catalog", "search_artifact_catalog", "rebuild_artifact_catalog", "export_research_artifact_md"),
            "files": ("trading/research/*.md", "trading/reports/**/*.md", "trading/decisions/*.md", "trading/research/.index/artifact-catalog-v2.json", "*.run-card.json", "*.validation-card.json", "trading/research/source-snapshots/*.json"),
            "templates": ("tradingcodex-mcp",),
            "tests": ("research-memory", "artifact-catalog"),
        },
        depends_on=("audit-ledger",),
        owned_capabilities=("research.memory",),
        validation=("pytest", "research-memory smoke checks"),
    ),
    HarnessComponent(
        id="investment-research-kernel",
        label="Investment Research Kernel",
        summary="Provides the pristine evidence, point-in-time replay, method-profile, causal calculation, forecasting, calibration, and model-evaluation contracts without depending on user or host-global skills.",
        status="core",
        tags=("improvement.workflow_quality", "improvement.research_memory", "improvement.validation_feedback"),
        surfaces={
            "services": ("research_specs", "investment_analysis", "forecasting", "evaluation_lab"),
            "skills": (
                "tcx-evidence",
                "tcx-data-qc",
                "tcx-scenarios",
                "tcx-forecast",
                "tcx-anti-overfit",
                "tcx-judgment",
            ),
            "files": (
                "trading/research/specs/*.json",
                "trading/research/replay-manifests/*.json",
                "trading/forecasts/*.jsonl",
                "trading/evaluations/**/*.json",
            ),
            "tests": ("research-method-profiles", "investment-analysis", "forecasting", "evaluation-profiles"),
        },
        depends_on=("research-memory", "artifact-quality-contract", "workflow-quality-gates"),
        owned_capabilities=(
            "research.pristine_baseline",
            "research.method_profiles",
            "forecast.lifecycle_and_calibration",
            "evaluation.profiled_corpus",
        ),
        validation=("pytest", "frozen replay evaluation", "generated workspace contract"),
    ),
    HarnessComponent(
        id="tcx-source-gate",
        label="External Data Source Gate",
        summary="Guides source-aware use of BYOR Codex, plugin, web, and data evidence without claiming control of user-installed capabilities.",
        status="core",
        tags=("guardrail.guidance", "improvement.workflow_quality"),
        surfaces={
            "skills": ("tcx-source-gate",),
            "instructions": ("AGENTS",),
            "templates": ("repo-skills",),
            "tests": ("external-data",),
        },
        depends_on=("workflow-quality-gates",),
        owned_capabilities=("evidence.external_source_gate",),
        validation=("pytest", "routing scenario tests"),
    ),
    HarnessComponent(
        id="codex-capability-inventory",
        label="Codex Capability Inventory",
        summary="Lists user-installed Codex MCP servers, skills, plugins, apps, and hooks without exposing configuration secrets or mutating Codex state.",
        status="core",
        tags=("guardrail.guidance", "guardrail.information_barrier"),
        surfaces={
            "services": ("codex_capabilities",),
            "mcp_tools": ("list_codex_capabilities",),
            "skills": ("tcx-server",),
            "frontend": ("System",),
            "tests": ("codex-capabilities", "product-web"),
        },
        depends_on=("secret-wall",),
        owned_capabilities=("codex.capabilities.inspect",),
        validation=("pytest", "frontend build", "python manage.py check"),
    ),
    HarnessComponent(
        id="secret-wall",
        label="Secret Wall",
        summary="Blocks raw broker secrets from workspace files, prompts, shell paths, and role context.",
        status="core",
        tags=("guardrail.enforcement", "guardrail.information_barrier"),
        surfaces={
            "hooks": ("UserPromptSubmit", "PreToolUse", "PermissionRequest"),
            "instructions": ("AGENTS",),
            "services": ("log_safety",),
            "templates": ("information-barriers", "codex-base"),
            "tests": ("secret-warning", "generated-workspace"),
        },
        depends_on=("audit-ledger",),
        owned_capabilities=("secret.block_workspace_storage",),
        validation=("pytest", "generated workspace contract"),
    ),
    HarnessComponent(
        id="policy-and-restricted-list",
        label="Policy And Restricted List",
        summary="Evaluates principals, capabilities, explicit deny rules, restricted symbols, and limits.",
        status="core",
        tags=("guardrail.enforcement",),
        surfaces={
            "services": ("policy",),
            "models": ("Principal", "Capability", "PolicyDecision", "RestrictedSymbol"),
            "mcp_tools": ("simulate_policy",),
            "templates": ("enforcement-guardrails",),
            "tests": ("policy",),
        },
        depends_on=("audit-ledger",),
        owned_capabilities=("policy.evaluate", "policy.restricted_list"),
        validation=("pytest", "python manage.py check"),
    ),
    HarnessComponent(
        id="approval-gate",
        label="Approval Gate",
        summary="Validates order tickets, JSON order inputs, and approval receipts before any execution-sensitive action.",
        status="core",
        tags=("guardrail.enforcement",),
        surfaces={
            "services": ("orders", "policy"),
            "skills": ("tcx-order-draft", "tcx-order-approve", "tcx-risk"),
            "mcp_tools": ("run_order_checks", "validate_approval_receipt", "request_order_approval"),
            "templates": ("enforcement-guardrails", "tradingcodex-mcp"),
            "tests": ("orders", "approval"),
        },
        depends_on=("policy-and-restricted-list", "audit-ledger"),
        owned_capabilities=("orders.approval_gate",),
        validation=("pytest", "python manage.py check"),
    ),
    HarnessComponent(
        id="execution-boundary",
        label="Execution Boundary",
        summary="Keeps execution behind an exact native-user mandate, approval, idempotency, connection, live gates, and audit checks without an execution agent.",
        status="core",
        tags=("guardrail.enforcement", "guardrail.information_barrier"),
        surfaces={
            "services": ("execution_gateway", "orders", "policy", "integrations"),
            "hooks": ("UserPromptSubmit native execution gate",),
            "skills": ("tcx-order-submit", "tcx-order-cancel"),
            "mcp_tools": ("get_order_status",),
            "templates": ("codex-base", "repo-skills", "paper-trading"),
            "tests": ("native execution parser", "hook", "execution", "MCP mutation absence"),
        },
        depends_on=("approval-gate", "policy-and-restricted-list", "audit-ledger"),
        owned_capabilities=("execution.boundary",),
        validation=("pytest", "native hook smoke", "MCP smoke checks"),
    ),
    HarnessComponent(
        id="broker-center",
        label="Broker Center",
        summary="Acts as the local broker control plane for connector state, provider capability profiles, source drift, account sync, mapping review, reconciliation, and audited service-gated execution.",
        status="experimental",
        tags=("guardrail.enforcement", "improvement.workflow_quality"),
        surfaces={
            "services": ("brokers", "portfolio", "orders"),
            "models": ("BrokerConnection", "BrokerAccount", "BrokerSyncRun", "ReconciliationRun", "InstrumentMap"),
            "mcp_tools": (
                "list_broker_connections",
                "get_broker_connection_status",
                "list_broker_adapter_providers",
                "render_broker_connector_scaffold",
                "register_broker_connector",
                "validate_broker_connector_build",
                "get_broker_capability_profile",
                "get_broker_instrument_constraints",
                "preview_order_translation",
                "sync_broker_account",
                "list_reconciliation_runs",
            ),
            "skills": ("tcx-server", "tcx-build"),
            "frontend": ("System",),
            "tests": ("broker-center", "portfolio-sync"),
        },
        depends_on=("policy-and-restricted-list", "audit-ledger"),
        owned_capabilities=("broker.connection", "broker.sync_read_only"),
        validation=("pytest", "python manage.py check"),
    ),
    HarnessComponent(
        id="order-ticket-lifecycle",
        label="Order Ticket Lifecycle",
        summary="Adds canonical order tickets, checks, approval scope binding, broker order timeline, and fills.",
        status="experimental",
        tags=("guardrail.enforcement", "improvement.workflow_quality"),
        surfaces={
            "services": ("orders", "brokers", "portfolio"),
            "models": ("OrderTicket", "OrderCheckRun", "OrderEvent", "BrokerOrder", "Fill"),
            "mcp_tools": ("create_order_ticket", "run_order_checks", "request_order_approval", "get_order_ticket", "list_order_tickets"),
            "frontend": ("System",),
            "tests": ("order-ticket", "approval-scope"),
        },
        depends_on=("approval-gate", "execution-boundary", "broker-center"),
        owned_capabilities=("orders.ticket", "orders.state_machine", "orders.approval_scope"),
        validation=("pytest", "python manage.py check"),
    ),
    HarnessComponent(
        id="audit-ledger",
        label="Audit Ledger",
        summary="Records policy, MCP, order, approval, execution, and hook events for review.",
        status="core",
        tags=("guardrail.enforcement", "improvement.validation_feedback"),
        surfaces={
            "services": ("audit",),
            "models": ("AuditEvent", "McpToolCall"),
            "mcp_tools": ("record_audit_event",),
            "templates": ("audit", "tradingcodex-mcp"),
            "tests": ("audit", "mcp-ledger"),
        },
        depends_on=(),
        owned_capabilities=("audit.write", "audit.review"),
        validation=("pytest", "MCP smoke checks"),
    ),
    HarnessComponent(
        id="skill-improvement-loop",
        label="Skill Improvement Loop",
        summary="Keeps user strategies, role-local optional skills, and additional-instruction overlays additive, explicitly activated, and visible through validation, projection, and manifest state without redefining the pristine core.",
        status="core",
        tags=("improvement.skill_evolution", "guardrail.guidance"),
        surfaces={
            "services": ("agents", "harness"),
            "files": (
                ".tradingcodex/mainagent/skill-change-proposals/*.yaml",
                ".tradingcodex/subagents/skills/*/*/SKILL.md",
                ".tradingcodex/subagents/skills/*/*/agents/tradingcodex.json",
                ".agents/skills/strategy-*/SKILL.md",
                ".tradingcodex/generated/projection-manifest.json",
                ".codex/agents/*.toml",
                ".agents/skills/*",
            ),
            "skills": ("tcx-plan", "tcx-workflow", "tcx-strategy"),
            "templates": ("repo-skills",),
            "tests": ("skill-proposals", "projection"),
        },
        depends_on=("fixed-role-dispatch",),
        owned_capabilities=("skill.proposal_loop", "customization.managed_overlay"),
        validation=("pytest", "generated workspace contract"),
    ),
    HarnessComponent(
        id="decision-memory-postmortems",
        label="Decision Memory Postmortems",
        summary="Preserves evidence-bound decision and process reviews so independently reviewed lessons can mature without a server-authored workflow.",
        status="core",
        tags=("improvement.postmortems", "improvement.validation_feedback"),
        surfaces={
            "skills": ("tcx-memory",),
            "services": ("postmortems", "decision_packages", "audit"),
            "templates": ("repo-skills",),
            "tests": ("postmortem",),
        },
        depends_on=("audit-ledger", "workflow-quality-gates"),
        owned_capabilities=("memory.postmortem_review",),
        validation=("pytest", "postmortem smoke checks"),
    ),
    HarnessComponent(
        id="paper-execution",
        label="Non-Live Execution",
        summary="Provides experimental local paper and validation-only submission paths behind the native-user approved action boundary.",
        status="experimental",
        tags=("guardrail.enforcement",),
        surfaces={
            "services": ("execution_gateway", "orders", "portfolio", "integrations"),
            "templates": ("paper-trading",),
            "mcp_tools": ("get_portfolio_snapshot",),
            "tests": ("paper-execution", "portfolio"),
        },
        depends_on=("execution-boundary", "approval-gate"),
        owned_capabilities=("execution.paper",),
        validation=("pytest", "native hook smoke"),
    ),
)


def list_harness_components() -> list[dict[str, Any]]:
    return [component.as_dict() for component in HARNESS_COMPONENTS]


def get_harness_component(component_id: str) -> dict[str, Any] | None:
    for component in HARNESS_COMPONENTS:
        if component.id == component_id:
            return component.as_dict()
    return None


def list_components_by_tag(tag: str) -> list[dict[str, Any]]:
    return [component.as_dict() for component in HARNESS_COMPONENTS if tag in component.tags]


def count_harness_component_tags() -> dict[str, int]:
    counts: dict[str, int] = {}
    for component in HARNESS_COMPONENTS:
        for tag in component.tags:
            top_level = tag.split(".", 1)[0]
            counts[top_level] = counts.get(top_level, 0) + 1
    return dict(sorted(counts.items()))
