# Generated by Django 5.2.5 on 2026-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTurnGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_id', models.CharField(max_length=80, unique=True)),
                ('authority_scope', models.CharField(choices=[('build', 'Build'), ('brain', 'Investment Brain'), ('strategy', 'Strategy')], default='build', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=16)),
                ('workspace_id', models.CharField(max_length=180)),
                ('workspace_path_hash', models.CharField(max_length=64)),
                ('session_id_hash', models.CharField(max_length=64)),
                ('turn_id_hash', models.CharField(max_length=64)),
                ('prompt_sha256', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_tool_use_id_hash', models.CharField(blank=True, max_length=64)),
                ('reservation_tool_name', models.CharField(blank=True, max_length=160)),
                ('reservation_arguments_hash', models.CharField(blank=True, max_length=64)),
                ('reservation_proof_hash', models.CharField(blank=True, max_length=64)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Workspace turn grant',
                'verbose_name_plural': 'Workspace turn grants',
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['workspace_id', 'workspace_path_hash', 'session_id_hash', 'status'], name='harness_build_session_idx'), models.Index(fields=['expires_at', 'status'], name='harness_build_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'workspace_path_hash', 'session_id_hash', 'turn_id_hash'), name='unique_build_grant_per_turn'), models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'reserved'])), fields=('workspace_id', 'workspace_path_hash', 'session_id_hash'), name='unique_active_build_grant_session')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=80, unique=True)),
                ('path_hash', models.CharField(max_length=64, unique=True)),
                ('project_name', models.CharField(max_length=180)),
                ('path', models.CharField(max_length=1024)),
                ('git_remote', models.CharField(blank=True, max_length=512)),
                ('git_branch', models.CharField(blank=True, max_length=180)),
                ('active_profile', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace context',
                'verbose_name_plural': 'Workspace contexts',
                'ordering': ['project_name', 'id'],
            },
        ),
    ]
