# Generated by TradingCodex on 2026-06-11

from django.db import migrations, models


def populate_workspace_ids(apps, schema_editor):
    WorkspaceContext = apps.get_model("harness", "WorkspaceContext")
    for context in WorkspaceContext.objects.all():
        context.workspace_id = context.workspace_id or f"legacy-{context.path_hash[:16]}"
        context.active_profile = context.active_profile or {
            "profile_id": "default-paper",
            "portfolio_id": "default-paper",
            "account_id": "local-paper",
            "strategy_id": "default-strategy",
            "label": "shared central paper profile",
            "shared": True,
        }
        context.save(update_fields=["workspace_id", "active_profile"])


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacecontext",
            name="workspace_id",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="workspacecontext",
            name="active_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(populate_workspace_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="workspacecontext",
            name="workspace_id",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
