# Generated by TradingCodex on 2026-06-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="EvidencePack"),
        migrations.DeleteModel(name="ResearchArtifactVersion"),
        migrations.DeleteModel(name="SourceSnapshot"),
        migrations.DeleteModel(name="ResearchArtifact"),
    ]
